package io.github.hmnshgpt455.beerorderservice.domain;

public enum BeerOrderStatusEnum {
    NEW, VALIDATED, VALIDATION_FAILED, INVENTORY_ALLOCATED,
    ALLOCATION_FAILED, PENDING_INVENTORY, DELIVERED, DELIVERY_FAILED, PICKED_UP, CANCELLED
}
