package io.github.hmnshgpt455.beerorderservice.domain;

public enum BeerOrderEventEnum {

    VALIDATE_ORDER, VALIDATION_PASSED, VALIDATION_FAILED,
    INVENTORY_ALLOCATION_SUCCESS, INVENTORY_ALLOCATION_FAILURE_NO_INVENTORY,
    INVENTORY_ALLOCATION_FAILURE_EXCEPTION, PICK_UP_ORDER, ALLOCATE_INVENTORY_TO_ORDER
}
