package guru.sfg.beer.order.service.domain;

public enum BeerOrderEvent {

    VALIDATE_ORDER, VALIDATION_PASSED, VALIDATION_FAILED,
    INVENTORY_ALLOCATION_SUCCESS, INVENTORY_ALLOCATION_FAILURE_NO_INVENTORY,
    INVENTORY_ALLOCATION_FAILURE_EXCEPTION, ORDER_PICKED_UP
}
